name: Build and deploy contents to Pages

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 9

            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Run validation checks
              run: |
                  pnpm lint
                  pnpm test

            - name: Build
              run: pnpm build

            - name: Upload build files
              uses: actions/upload-artifact@v4
              with:
                  name: app-build
                  path: ./dist

    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        concurrency:
            group: ${{ github.workflow }}-${{ github.ref }}
            cancel-in-progress: true
        steps:
            - uses: actions/checkout@v4

            - name: Download build files
              uses: actions/download-artifact@v4
              with:
                  name: app-build
                  path: ./dist

            - name: Host app in GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: gh-pages
                  folder: ${{ github.workspace }}/dist
                  git-config-name: github-actions[bot]
                  git-config-email: github-actions[bot]@users.noreply.github.com
